import { LegalLayout, Section } from "./LegalLayout";

function TermsAndConditions() {
    return (
        <LegalLayout title="Terms & Conditions" lastUpdated="9 July 2026">

            <p>
                These Terms & Conditions ("Terms") govern access to and use of CareerForge AI
                (the "Platform"), operated by <strong className="text-white">[Company Legal Name]</strong>,
                a company registered in <strong className="text-white">[State], India</strong>
                ("we", "us", "our"). By creating an account you agree to these Terms. If you do
                not agree, please do not register or use the Platform.
            </p>

            <Section number="1" title="Eligibility">
                <p>
                    You must be at least 18 years old, or the age of legal majority in your
                    jurisdiction, to create an account. By registering, you confirm the
                    information you provide is accurate and that you have the legal capacity to
                    enter into this agreement.
                </p>
            </Section>

            <Section number="2" title="Your account">
                <p>
                    You are responsible for keeping your login credentials confidential and for
                    all activity that happens under your account. Tell us immediately at{" "}
                    <span className="text-white">[support@yourdomain.com]</span> if you suspect
                    unauthorized access.
                </p>
            </Section>

            <Section number="3" title="What the Platform does">
                <p>
                    CareerForge AI provides AI-assisted tools including chat assistance, coding
                    help, resume tailoring, ATS scoring, and related image and document
                    generation features. Outputs are generated by AI models and are provided as
                    a starting point — you're responsible for reviewing and verifying anything
                    you use for real applications, interviews, or professional decisions.
                </p>
            </Section>

            <Section number="4" title="Credits, plans, and payment">
                <p>
                    New accounts receive a starting allocation of free credits. Continued or
                    additional usage may require purchasing a paid plan or top-up credits. All
                    payment terms, pricing, billing cycles, and refund rules are set out in our{" "}
                    <span className="text-amber-300 font-semibold">Payment & Credits Policy</span>,
                    which forms part of these Terms.
                </p>
            </Section>

            <Section number="5" title="Acceptable use">
                <p>You agree not to:</p>
                <ul className="list-disc pl-5 space-y-1.5 marker:text-fuchsia-400/60">
                    <li>Use the Platform for any unlawful purpose, or to generate content that infringes others' rights.</li>
                    <li>Attempt to bypass credit limits, rate limits, or security controls.</li>
                    <li>Resell, scrape, or redistribute Platform outputs at scale without written permission.</li>
                    <li>Upload malicious files or attempt to compromise the Platform's infrastructure.</li>
                    <li>Impersonate another person or misrepresent your affiliation with any entity.</li>
                </ul>
            </Section>

            <Section number="6" title="Your content">
                <p>
                    You retain ownership of documents, resumes, and other content you upload. You
                    grant us a limited license to process that content solely to provide the
                    service (e.g. sending it to an AI model to generate a response). We do not
                    sell your content.
                </p>
            </Section>

            <Section number="7" title="Privacy">
                <p>
                    We collect the information you provide at signup (name, email, mobile number,
                    optional profile photo and description) and usage data needed to operate the
                    Platform, prevent abuse, and process payments. We do not share your personal
                    data with third parties except payment processors (see Section 4), service
                    providers who help us run the Platform, or where required by law. Full detail
                    on data retention and your rights will live in a dedicated Privacy Policy at{" "}
                    <span className="text-white">[link]</span>.
                </p>
            </Section>

            <Section number="8" title="Disclaimers and liability">
                <p>
                    The Platform is provided "as is." AI-generated content may contain errors —
                    we don't guarantee outcomes such as job offers, interview results, or ATS
                    pass rates. To the fullest extent permitted by law, our liability for any
                    claim relating to the Platform is limited to the amount you paid us in the
                    12 months before the claim arose.
                </p>
            </Section>

            <Section number="9" title="Suspension and termination">
                <p>
                    We may suspend or terminate accounts that violate these Terms, engage in
                    fraud, or abuse the Platform. You may close your account at any time from
                    account settings; any unused credits are handled per the Payment & Credits
                    Policy.
                </p>
            </Section>

            <Section number="10" title="Changes to these Terms">
                <p>
                    We may update these Terms from time to time. Material changes will be
                    notified by email or in-app notice before they take effect. Continued use
                    after changes take effect means you accept the updated Terms.
                </p>
            </Section>

            <Section number="11" title="Governing law">
                <p>
                    These Terms are governed by the laws of India. Disputes are subject to the
                    exclusive jurisdiction of the courts of{" "}
                    <span className="text-white">[City], [State]</span>.
                </p>
            </Section>

            <Section number="12" title="Contact">
                <p>
                    Questions about these Terms can be sent to{" "}
                    <span className="text-white">[support@yourdomain.com]</span> or{" "}
                    <span className="text-white">[registered postal address]</span>.
                </p>
            </Section>
        </LegalLayout>
    );
}

export default TermsAndConditions;